import { Injectable } from '@angular/core';
import { Breed } from '../models/breed.model';
import { BaseService } from './base.service';

@Injectable({
  providedIn: 'root',
})
export class BreedService extends BaseService<Breed> {
  constructor() {
    super();
    // Add mock data
    this.data = [
      { id: 'b1', name: 'Affenpinscher', size: 'small' },
      { id: 'b2', name: 'Afghan Hound', size: 'large' },
      { id: 'b3', name: 'Aidi', size: 'medium' },
      { id: 'b4', name: 'Airedale Terrier', size: 'large' },
      { id: 'b5', name: 'Akita', size: 'large' },
      { id: 'b6', name: 'Alaskan Malamute', size: 'large' },
      { id: 'b7', name: 'American Bulldog', size: 'large' },
      { id: 'b8', name: 'American Cocker Spaniel', size: 'medium' },
      { id: 'b9', name: 'American Eskimo Dog', size: 'small' },
      { id: 'b10', name: 'American Foxhound', size: 'large' },
      { id: 'b11', name: 'American Pit Bull Terrier', size: 'medium' },
      { id: 'b12', name: 'American Staffordshire Terrier', size: 'medium' },
      { id: 'b13', name: 'American Water Spaniel', size: 'medium' },
      { id: 'b14', name: 'Australian Cattle Dog', size: 'medium' },
      { id: 'b15', name: 'Australian Shepherd', size: 'medium' },
      { id: 'b16', name: 'Australian Terrier', size: 'small' },
      { id: 'b17', name: 'Barbet', size: 'medium' },
      { id: 'b18', name: 'Basenji', size: 'medium' },
      { id: 'b19', name: 'Basset Hound', size: 'medium' },
      { id: 'b20', name: 'Beagle', size: 'medium' },
      { id: 'b21', name: 'Bearded Collie', size: 'large' },
      { id: 'b22', name: 'Bedlington Terrier', size: 'medium' },
      { id: 'b23', name: 'Bernese Mountain Dog', size: 'large' },
      { id: 'b24', name: 'Bichon Frise', size: 'small' },
      { id: 'b25', name: 'Black and Tan Coonhound', size: 'large' },
      { id: 'b26', name: 'Bloodhound', size: 'large' },
      { id: 'b27', name: 'Border Collie', size: 'medium' },
      { id: 'b28', name: 'Border Terrier', size: 'small' },
      { id: 'b29', name: 'Borzoi', size: 'large' },
      { id: 'b30', name: 'Boston Terrier', size: 'small' },
      { id: 'b31', name: 'Bouvier des Flandres', size: 'large' },
      { id: 'b32', name: 'Boxer', size: 'large' },
      { id: 'b33', name: 'Briard', size: 'large' },
      { id: 'b34', name: 'Brittany', size: 'medium' },
      { id: 'b35', name: 'Brussels Griffon', size: 'small' },
      { id: 'b36', name: 'Bull Terrier', size: 'medium' },
      { id: 'b37', name: 'Bulldog', size: 'medium' },
      { id: 'b38', name: 'Bullmastiff', size: 'large' },
      { id: 'b39', name: 'Cairn Terrier', size: 'small' },
      { id: 'b40', name: 'Canaan Dog', size: 'medium' },
      { id: 'b41', name: 'Cane Corso', size: 'large' },
      { id: 'b42', name: 'Cavalier King Charles Spaniel', size: 'small' },
      { id: 'b43', name: 'Chesapeake Bay Retriever', size: 'large' },
      { id: 'b44', name: 'Chihuahua', size: 'small' },
      { id: 'b45', name: 'Chinese Crested', size: 'small' },
      { id: 'b46', name: 'Chinese Shar-Pei', size: 'medium' },
      { id: 'b47', name: 'Chow Chow', size: 'medium' },
      { id: 'b48', name: 'Clumber Spaniel', size: 'large' },
      { id: 'b49', name: 'Cocker Spaniel', size: 'medium' },
      { id: 'b50', name: 'Collie', size: 'large' },
      { id: 'b51', name: 'Coton de Tulear', size: 'small' },
      { id: 'b52', name: 'Curly-Coated Retriever', size: 'large' },
      { id: 'b53', name: 'Dachshund', size: 'small' },
      { id: 'b54', name: 'Dalmatian', size: 'large' },
      { id: 'b55', name: 'Dandie Dinmont Terrier', size: 'small' },
      { id: 'b56', name: 'Doberman Pinscher', size: 'large' },
      { id: 'b57', name: 'Dogue de Bordeaux', size: 'large' },
      { id: 'b58', name: 'English Cocker Spaniel', size: 'medium' },
      { id: 'b59', name: 'English Setter', size: 'large' },
      { id: 'b60', name: 'English Springer Spaniel', size: 'medium' },
      { id: 'b61', name: 'English Toy Spaniel', size: 'small' },
      { id: 'b62', name: 'Entlebucher Mountain Dog', size: 'medium' },
      { id: 'b63', name: 'Field Spaniel', size: 'medium' },
      { id: 'b64', name: 'Finnish Lapphund', size: 'medium' },
      { id: 'b65', name: 'Finnish Spitz', size: 'medium' },
      { id: 'b66', name: 'Flat-Coated Retriever', size: 'large' },
      { id: 'b67', name: 'French Bulldog', size: 'small' },
      { id: 'b68', name: 'German Pinscher', size: 'medium' },
      { id: 'b69', name: 'German Shepherd Dog', size: 'large' },
      { id: 'b70', name: 'German Shorthaired Pointer', size: 'large' },
      { id: 'b71', name: 'German Wirehaired Pointer', size: 'large' },
      { id: 'b72', name: 'Giant Schnauzer', size: 'large' },
      { id: 'b73', name: 'Glen of Imaal Terrier', size: 'small' },
      { id: 'b74', name: 'Golden Retriever', size: 'large' },
      { id: 'b75', name: 'Gordon Setter', size: 'large' },
      { id: 'b76', name: 'Great Dane', size: 'large' },
      { id: 'b77', name: 'Great Pyrenees', size: 'large' },
      { id: 'b78', name: 'Greater Swiss Mountain Dog', size: 'large' },
      { id: 'b79', name: 'Greyhound', size: 'large' },
      { id: 'b80', name: 'Harrier', size: 'medium' },
      { id: 'b81', name: 'Havanese', size: 'small' },
      { id: 'b82', name: 'Hungarian Vizsla', size: 'medium' },
      { id: 'b83', name: 'Husky', size: 'large' },
      { id: 'b84', name: 'Ibizan Hound', size: 'large' },
      { id: 'b85', name: 'Irish Red and White Setter', size: 'large' },
      { id: 'b86', name: 'Irish Setter', size: 'large' },
      { id: 'b87', name: 'Irish Terrier', size: 'medium' },
      { id: 'b88', name: 'Irish Water Spaniel', size: 'large' },
      { id: 'b89', name: 'Irish Wolfhound', size: 'large' },
      { id: 'b90', name: 'Italian Greyhound', size: 'small' },
      { id: 'b91', name: 'Jack Russell Terrier', size: 'small' },
      { id: 'b92', name: 'Japanese Chin', size: 'small' },
      { id: 'b93', name: 'Karelian Bear Dog', size: 'medium' },
      { id: 'b94', name: 'Keeshond', size: 'medium' },
      { id: 'b95', name: 'Kerry Blue Terrier', size: 'medium' },
      { id: 'b96', name: 'Komondor', size: 'large' },
      { id: 'b97', name: 'Kooikerhondje', size: 'small' },
      { id: 'b98', name: 'Kuvasz', size: 'large' },
      { id: 'b99', name: 'Labrador Retriever', size: 'large' },
      { id: 'b100', name: 'Lagotto Romagnolo', size: 'medium' },
      { id: 'b101', name: 'Lakeland Terrier', size: 'small' },
      { id: 'b102', name: 'Lancashire Heeler', size: 'small' },
      { id: 'b103', name: 'Leonberger', size: 'large' },
      { id: 'b104', name: 'Lhasa Apso', size: 'small' },
      { id: 'b105', name: 'Löwchen', size: 'small' },
      { id: 'b106', name: 'Maltese', size: 'small' },
      { id: 'b107', name: 'Manchester Terrier', size: 'small' },
      { id: 'b108', name: 'Mastiff', size: 'large' },
      { id: 'b109', name: 'Miniature American Shepherd', size: 'small' },
      { id: 'b110', name: 'Miniature Bull Terrier', size: 'small' },
      { id: 'b111', name: 'Miniature Pinscher', size: 'small' },
      { id: 'b112', name: 'Miniature Schnauzer', size: 'small' },
      { id: 'b113', name: 'Neapolitan Mastiff', size: 'large' },
      { id: 'b114', name: 'Newfoundland', size: 'large' },
      { id: 'b115', name: 'Norfolk Terrier', size: 'small' },
      { id: 'b116', name: 'Norwegian Buhund', size: 'medium' },
      { id: 'b117', name: 'Norwegian Elkhound', size: 'medium' },
      { id: 'b118', name: 'Norwegian Lundehund', size: 'small' },
      { id: 'b119', name: 'Norwich Terrier', size: 'small' },
      { id: 'b120', name: 'Old English Sheepdog', size: 'large' },
      { id: 'b121', name: 'Otterhound', size: 'large' },
      { id: 'b122', name: 'Papillon', size: 'small' },
      { id: 'b123', name: 'Pekingese', size: 'small' },
      { id: 'b124', name: 'Pembroke Welsh Corgi', size: 'small' },
      { id: 'b125', name: 'Petit Basset Griffon Vendéen', size: 'medium' },
      { id: 'b126', name: 'Pharaoh Hound', size: 'large' },
      { id: 'b127', name: 'Plott', size: 'medium' },
      { id: 'b128', name: 'Pointer', size: 'large' },
      { id: 'b129', name: 'Pomeranian', size: 'small' },
      { id: 'b130', name: 'Poodle', size: 'medium' },
      { id: 'b131', name: 'Portuguese Water Dog', size: 'medium' },
      { id: 'b132', name: 'Pug', size: 'small' },
      { id: 'b133', name: 'Rat Terrier', size: 'small' },
      { id: 'b134', name: 'Redbone Coonhound', size: 'medium' },
      { id: 'b135', name: 'Rhodesian Ridgeback', size: 'large' },
      { id: 'b136', name: 'Rottweiler', size: 'large' },
      { id: 'b137', name: 'Rough Collie', size: 'large' },
      { id: 'b138', name: 'Russian Toy', size: 'small' },
      { id: 'b139', name: 'Saint Bernard', size: 'large' },
      { id: 'b140', name: 'Saluki', size: 'large' },
      { id: 'b141', name: 'Samoyed', size: 'medium' },
      { id: 'b142', name: 'Schipperke', size: 'small' },
      { id: 'b143', name: 'Scottish Deerhound', size: 'large' },
      { id: 'b144', name: 'Scottish Terrier', size: 'small' },
      { id: 'b145', name: 'Sealyham Terrier', size: 'small' },
      { id: 'b146', name: 'Shetland Sheepdog', size: 'small' },
      { id: 'b147', name: 'Shiba Inu', size: 'small' },
      { id: 'b148', name: 'Shih Tzu', size: 'small' },
      { id: 'b149', name: 'Siberian Husky', size: 'large' },
      { id: 'b150', name: 'Silky Terrier', size: 'small' },
      { id: 'b151', name: 'Skye Terrier', size: 'small' },
      { id: 'b152', name: 'Sloughi', size: 'large' },
      { id: 'b153', name: 'Slovak Cuvac', size: 'large' },
      { id: 'b154', name: 'Slovenský kopov', size: 'medium' },
      { id: 'b155', name: 'Slovak Rough-haired Pointer', size: 'large' },
      { id: 'b156', name: 'Soft Coated Wheaten Terrier', size: 'medium' },
      { id: 'b157', name: 'Spanish Water Dog', size: 'medium' },
      { id: 'b158', name: 'Spinone Italiano', size: 'large' },
      { id: 'b159', name: 'Staffordshire Bull Terrier', size: 'medium' },
      { id: 'b160', name: 'Standard Schnauzer', size: 'medium' },
      { id: 'b161', name: 'Sussex Spaniel', size: 'medium' },
      { id: 'b162', name: 'Swedish Vallhund', size: 'small' },
      { id: 'b163', name: 'Tibetan Mastiff', size: 'large' },
      { id: 'b164', name: 'Tibetan Spaniel', size: 'small' },
      { id: 'b165', name: 'Tibetan Terrier', size: 'medium' },
      { id: 'b166', name: 'Toy Fox Terrier', size: 'small' },
      { id: 'b167', name: 'Vizsla', size: 'medium' },
      { id: 'b168', name: 'Weimaraner', size: 'large' },
      { id: 'b169', name: 'Welsh Springer Spaniel', size: 'medium' },
      { id: 'b170', name: 'Welsh Terrier', size: 'small' },
      { id: 'b171', name: 'West Highland White Terrier', size: 'small' },
      { id: 'b172', name: 'Whippet', size: 'medium' },
      { id: 'b173', name: 'Wire Fox Terrier', size: 'small' },
      { id: 'b174', name: 'Wirehaired Pointing Griffon', size: 'large' },
      { id: 'b175', name: 'Xoloitzcuintli', size: 'medium' },
      { id: 'b176', name: 'Yorkshire Terrier', size: 'small' },
    ];
  }
}
