import { Injectable } from '@angular/core';
import { take } from 'rxjs';
import { FIRESTORE_COLLECTION } from '../constants/firestore-collections';
import { Breed } from '../models/breed.model';
import { BaseService } from './base.service';

@Injectable({
  providedIn: 'root',
})
export class BreedService extends BaseService<Breed> {
  private defaults: Breed[] = [
    // Kleine rassen
    { name: 'Affenpinscher', size: 'small' },
    { name: 'Amerikaanse Toy Terriër', size: 'small' },
    { name: 'Bichon Frisé', size: 'small' },
    { name: 'Bologneezer', size: 'small' },
    { name: 'Boston Terriër', size: 'small' },
    { name: 'Brusselse Griffon', size: 'small' },
    { name: 'Cairn Terriër', size: 'small' },
    { name: 'Cavalier King Charles Spaniël', size: 'small' },
    { name: 'Chihuahua', size: 'small' },
    { name: 'Chinese Naakthond', size: 'small' },
    { name: 'Coton de Tuléar', size: 'small' },
    { name: 'Dwergkeeshond (Pomeranian)', size: 'small' },
    { name: 'Dwergpinscher', size: 'small' },
    { name: 'Dwergpoedel', size: 'small' },
    { name: 'Dwergschnauzer', size: 'small' },
    { name: 'Engelse Toy Terriër', size: 'small' },
    { name: 'Franse Bulldog', size: 'small' },
    { name: 'Havanezer', size: 'small' },
    { name: 'Italiaans Windhondje', size: 'small' },
    { name: 'Jack Russell Terriër', size: 'small' },
    { name: 'Japanse Chin', size: 'small' },
    { name: 'Lhasa Apso', size: 'small' },
    { name: 'Leeuwhondje (Löwchen)', size: 'small' },
    { name: 'Maltezer', size: 'small' },
    { name: 'Mopshond (Pug)', size: 'small' },
    { name: 'Norfolk Terriër', size: 'small' },
    { name: 'Norwich Terriër', size: 'small' },
    { name: 'Papillon (Vlinderhondje)', size: 'small' },
    { name: 'Pekingees', size: 'small' },
    { name: 'Russische Toy Terriër', size: 'small' },
    { name: 'Schipperke', size: 'small' },
    { name: 'Schotse Terriër', size: 'small' },
    { name: 'Sealyham Terriër', size: 'small' },
    { name: 'Shih Tzu', size: 'small' },
    { name: 'Teckel (Dwerg/Kaninchen)', size: 'small' },
    { name: 'Tibetaanse Spaniël', size: 'small' },
    { name: 'Vlinderhondje (Papillon)', size: 'small' },
    { name: 'West Highland White Terriër (Westie)', size: 'small' },
    { name: 'Yorkshire Terriër', size: 'small' },
    { name: 'Kruising (klein)', size: 'small' },

    // Middelgrote rassen
    { name: 'Aidi', size: 'medium' },
    { name: 'Amerikaanse Cocker Spaniël', size: 'medium' },
    { name: 'Amerikaanse Staffordshire Terriër', size: 'medium' },
    { name: 'Amerikaanse Water Spaniël', size: 'medium' },
    { name: 'Australische Herder (Australian Shepherd)', size: 'medium' },
    { name: 'Australische Kelpie', size: 'medium' },
    { name: 'Australische Veehond (Cattle Dog)', size: 'medium' },
    { name: 'Basenji', size: 'medium' },
    { name: 'Basset Hound', size: 'medium' },
    { name: 'Beagle', size: 'medium' },
    { name: 'Bearded Collie (kleinere variant)', size: 'medium' },
    { name: 'Bedlington Terriër', size: 'medium' },
    { name: 'Boerenfox', size: 'medium' },
    { name: 'Border Collie', size: 'medium' },
    { name: 'Border Terriër', size: 'medium' },
    { name: 'Bretonse Spaniël (Epagneul Breton)', size: 'medium' },
    { name: 'Bull Terriër', size: 'medium' },
    { name: 'Chow Chow', size: 'medium' },
    { name: 'Clumber Spaniël', size: 'medium' },
    { name: 'Engelse Cocker Spaniël', size: 'medium' },
    { name: 'Engelse Springer Spaniël', size: 'medium' },
    { name: 'Drentsche Patrijshond', size: 'medium' },
    { name: 'Duitse Pinscher', size: 'medium' },
    { name: 'Entlebucher Sennenhond', size: 'medium' },
    { name: 'Finse Lappenhond', size: 'medium' },
    { name: 'Finse Spits', size: 'medium' },
    { name: 'Foxterriër (Draadhaar)', size: 'medium' },
    { name: 'Foxterriër (Gladhaar)', size: 'medium' },
    { name: 'Friese Stabij', size: 'medium' },
    { name: 'Heidewachtel', size: 'medium' },
    { name: 'Hollandse Herder', size: 'medium' },
    { name: 'Ierse Terriër', size: 'medium' },
    { name: 'IJslandse Hond', size: 'medium' },
    { name: 'Keeshond (Groot)', size: 'medium' },
    { name: 'Kerry Blue Terriër', size: 'medium' },
    { name: 'Kooikerhondje', size: 'medium' },
    { name: 'Kromfohrländer', size: 'medium' },
    { name: 'Labradoodle (medium)', size: 'medium' },
    { name: 'Lagotto Romagnolo', size: 'medium' },
    { name: 'Manchester Terriër', size: 'medium' },
    { name: 'Markiesje', size: 'medium' },
    { name: 'Middelgrote Poedel', size: 'medium' },
    { name: 'Middenslagschnauzer', size: 'medium' },
    { name: 'Noorse Elandhond', size: 'medium' },
    { name: 'Nova Scotia Duck Tolling Retriever', size: 'medium' },
    { name: 'Oostenrijkse Pinscher', size: 'medium' },
    { name: 'Parson Russell Terriër', size: 'medium' },
    { name: 'Pitbull Terriër', size: 'medium' },
    { name: 'Poolse Herdershond (Laagland)', size: 'medium' },
    { name: 'Portugese Waterhond', size: 'medium' },
    { name: 'Puli', size: 'medium' },
    { name: 'Pyrenese Herdershond', size: 'medium' },
    { name: 'Samojeed', size: 'medium' },
    { name: 'Schnauzer', size: 'medium' },
    { name: 'Shar Pei', size: 'medium' },
    { name: 'Sheltie (Shetland Sheepdog)', size: 'medium' },
    { name: 'Shiba Inu', size: 'medium' },
    { name: 'Siberische Husky', size: 'medium' },
    { name: 'Soft Coated Wheaten Terriër', size: 'medium' },
    { name: 'Spaanse Waterhond', size: 'medium' },
    { name: 'Staffordshire Bull Terriër', size: 'medium' },
    { name: 'Teckel (Standaard)', size: 'medium' },
    { name: 'Tibetaanse Terriër', size: 'medium' },
    { name: 'Welsh Corgi Cardigan', size: 'medium' },
    { name: 'Welsh Corgi Pembroke', size: 'medium' },
    { name: 'Welsh Springer Spaniël', size: 'medium' },
    { name: 'Welsh Terriër', size: 'medium' },
    { name: 'Whippet', size: 'medium' },
    { name: 'Kruising (middel)', size: 'medium' },

    // Grote rassen
    { name: 'Afghaanse Windhond', size: 'large' },
    { name: 'Airedale Terriër', size: 'large' },
    { name: 'Akita Inu', size: 'large' },
    { name: 'Alaskan Malamute', size: 'large' },
    { name: 'Amerikaanse Akita', size: 'large' },
    { name: 'Amerikaanse Bulldog', size: 'large' },
    { name: 'Argentijnse Dog', size: 'large' },
    { name: 'Barbet', size: 'large' },
    { name: 'Barsoi', size: 'large' },
    { name: 'Bearded Collie', size: 'large' },
    { name: 'Beauceron', size: 'large' },
    { name: 'Belgische Herder (Groenendaeler)', size: 'large' },
    { name: 'Belgische Herder (Laekense)', size: 'large' },
    { name: 'Belgische Herder (Mechelse)', size: 'large' },
    { name: 'Belgische Herder (Tervuerense)', size: 'large' },
    { name: 'Berner Sennenhond', size: 'large' },
    { name: 'Bloedhond', size: 'large' },
    { name: 'Bobtail (Old English Sheepdog)', size: 'large' },
    { name: 'Boerboel', size: 'large' },
    { name: 'Bordeauxdog', size: 'large' },
    { name: 'Bouvier des Flandres', size: 'large' },
    { name: 'Boxer', size: 'large' },
    { name: 'Briard', size: 'large' },
    { name: 'Bullmastiff', size: 'large' },
    { name: 'Cane Corso', size: 'large' },
    { name: 'Chesapeake Bay Retriever', size: 'large' },
    { name: 'Dalmatiër', size: 'large' },
    { name: 'Dobermann', size: 'large' },
    { name: 'Dogo Argentino', size: 'large' },
    { name: 'Duitse Dog', size: 'large' },
    { name: 'Duitse Herder', size: 'large' },
    { name: 'Duitse Staande Hond (Draadhaar)', size: 'large' },
    { name: 'Duitse Staande Hond (Korthaar)', size: 'large' },
    { name: 'Duitse Staande Hond (Langhaar)', size: 'large' },
    { name: 'Engelse Bulldog', size: 'large' },
    { name: 'Engelse Setter', size: 'large' },
    { name: 'Flat-Coated Retriever', size: 'large' },
    { name: 'Galgo Español', size: 'large' },
    { name: 'Golden Retriever', size: 'large' },
    { name: 'Gordon Setter', size: 'large' },
    { name: 'Greyhound', size: 'large' },
    { name: 'Grote Poedel (Koningspoedel)', size: 'large' },
    { name: 'Grote Zwitserse Sennenhond', size: 'large' },
    { name: 'Hovawart', size: 'large' },
    { name: 'Ierse Setter', size: 'large' },
    { name: 'Ierse Water Spaniël', size: 'large' },
    { name: 'Ierse Wolfshond', size: 'large' },
    { name: 'Komondor', size: 'large' },
    { name: 'Kuvasz', size: 'large' },
    { name: 'Labradoodle (groot)', size: 'large' },
    { name: 'Labrador Retriever', size: 'large' },
    { name: 'Landseer ECT', size: 'large' },
    { name: 'Leonberger', size: 'large' },
    { name: 'Mastiff', size: 'large' },
    { name: 'Mastino Napoletano', size: 'large' },
    { name: 'Newfoundlander', size: 'large' },
    { name: 'Pointer', size: 'large' },
    { name: 'Pyreneese Berghond', size: 'large' },
    { name: 'Rhodesian Ridgeback', size: 'large' },
    { name: 'Riesenschnauzer', size: 'large' },
    { name: 'Rottweiler', size: 'large' },
    { name: 'Saarlooswolfhond', size: 'large' },
    { name: 'Saluki', size: 'large' },
    { name: 'Schotse Herder (Collie)', size: 'large' },
    { name: 'Sint Bernard', size: 'large' },
    { name: 'Slowaakse Tchouvatch', size: 'large' },
    { name: 'Tatra', size: 'large' },
    { name: 'Tibetaanse Mastiff', size: 'large' },
    { name: 'Tosa Inu', size: 'large' },
    { name: 'Tsjechoslowaakse Wolfhond', size: 'large' },
    { name: 'Weimaraner', size: 'large' },
    { name: 'Witte Herder', size: 'large' },
    { name: 'Zwarte Russische Terriër', size: 'large' },
    { name: 'Kruising (groot)', size: 'large' },

    // Populaire kruisingen / mixen
    { name: 'Boomer', size: 'small' },
    { name: 'Labradoodle (klein)', size: 'small' },
    { name: 'Goldendoodle', size: 'large' },
    { name: 'Cockapoo', size: 'medium' },
    { name: 'Maltipoo', size: 'small' },
    { name: 'Pomsky', size: 'medium' },
    { name: 'Puggle', size: 'small' },
    { name: 'Schnoodle', size: 'medium' },
    { name: 'Kruising', size: 'medium' },
  ];

  constructor() {
    super(FIRESTORE_COLLECTION.breeds);
    this.initializeDefaults();
  }

  private initializeDefaults() {
    this.getData$()
      .pipe(take(1))
      .subscribe((existingBreeds) => {
        const breedsToAdd = this.defaults.filter(
          (defaultBreed) =>
            !existingBreeds.some(
              (existingBreed) =>
                existingBreed.name.toLowerCase() ===
                defaultBreed.name.toLowerCase(),
            ),
        );

        if (breedsToAdd.length > 0) {
          breedsToAdd.forEach((breed) => {
            this.add(breed).subscribe();
          });
        }
      });
  }
}
